unit uHelp;

interface

const C_HELPFILE = 'Testgrip.chm';


{
Note: this next bit is generated by going to the
 "Context Tool" in Help&Manual -> Export map file

 and entering the following custom export lines:

const HelpTopic_<%TOPICID%> = <%TOPIC_HELPCONTEXT%>;

const HelpAnchor_<%TOPICID%>_<%ANCHORID%> = <%TOPIC_HELPCONTEXT%>;
}

const HelpTopic_Advanced_settings = 100;
const HelpTopic_Chapter_2 = 101;
const HelpTopic_Code_view = 102;
const HelpTopic_Complex_impliers = 103;
const HelpTopic_Equals = 104;
const HelpTopic_Extra_includes = 105;
const HelpTopic_Extra_variables = 106;
const HelpTopic_Implies = 107;
const HelpTopic_Introduction = 108;
const HelpTopic_Matrix_tests_entry = 109;
const HelpTopic_Overview = 110;
const HelpTopic_Parameters = 111;
const HelpTopic_Setup_code = 113;
const HelpTopic_Test_definition = 114;



implementation

end.
